/**
 * Spotify Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, unknown } from '../schema';

export interface QueueObject {
  /** The currently playing track or episode. Can be `null`. */
  currentlyPlaying?: unknown;
  /** The tracks or episodes in the queue. Can be empty. */
  queue?: unknown[];
}

export const queueObjectSchema: Schema<QueueObject> = object({
  currentlyPlaying: ['currently_playing', optional(unknown())],
  queue: ['queue', optional(array(unknown()))],
});
