/**
 * Spotify Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Track1 {
  /** Spotify URI */
  uri?: string;
}

export const track1Schema: Schema<Track1> = object({
  uri: ['uri', optional(string())],
});
