/**
 * Spotify Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type9Enum
 */
export enum Type9Enum {
  Audiobook = 'audiobook',
}

/**
 * Schema for Type9Enum
 */
export const type9EnumSchema: Schema<Type9Enum> = stringEnum(Type9Enum);
