/**
 * Spotify Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type6Enum
 */
export enum Type6Enum {
  AudioFeatures = 'audio_features',
}

/**
 * Schema for Type6Enum
 */
export const type6EnumSchema: Schema<Type6Enum> = stringEnum(Type6Enum);
